name: CI
on:
  workflow_call:
jobs:
  Called:
    runs-on: windows-latest
    env:
      ACTIONS_RUNNER_DEBUG: true # Enable debug logging
      ACTIONS_STEP_DEBUG: true # Enable debug logging
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          repository: aneeshchackov/master
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: |
            README.md 
            HELP.md
            Secrets.txt #Invalid file, added for testing
            TEST_1.md
            TEST_2.md
          if-no-files-found: error
          retention-days: 0
